spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LiYanLance/springcloud-config-repository.git
          search-paths: micro-service
          timeout: 60
server:
  port: 8888